= Shading mask

Shading masks are synthetic diagrams that represent the incident radiation on a given surface for all possible altitudes and azimuth angles of the incoming rays. They are normally represented using a circular diagram where:

- the azimuth coordinate runs on the circumference;
- the altitude coordinate runs from the circumference to the center of the circle;
- white and light grey regions indicate none to little shading from the surroundings (buildings, trees, etc) for that specific interval of azimuth and altitude angles;
- dark grey and black regions indicate heavy to complete coverage from the surroundings (buildings, trees, etc) for that specific interval of azimuth and altitude angles.

== Implementation

Given a meshed geometry, a Bounding Volume Hierarchy is constructed to partition the scene. Then, for each surface of interest, raytracing is used to build a shading mask matrix of size stem:[N_{Az} \times N_{Alt}], where stem:[N_{Az}] and stem:[N_{Alt}] are determined by the discretization of the azimuth and altitude coordinates.
