:feelpp: Feel++
:cpp: C++
:project: solar-shading 

= {feelpp} Solar Shading Project
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>
v2: 

image:https://github.com/feelpp/solar-shading/workflows/CI/badge.svg[CI]

This repository provides a basic starting point for a {feelpp} application including:

- [x] {feelpp} applications in {cpp} to use {feelpp} and {feelpp} toolboxes in `src`
- [x] documentation using asciidoc and antora
- [x] python {feelpp} notebooks that can be downloaded from the documentation
- [x] continuous integration including tests for the {cpp} applications
- [x] docker image generation for the project

The documentation for solar-shading is available at link:https://feelpp.github.io/solar-shading[here] and you can build on it for your project by enabling the link:https://docs.github.com/en/pages[github pages] for your repository.


== Updating the {project} version

The version of the project is defined in the files `CMakeLists.txt`, `docs/antora.yml` and `docs/package.json`. 
You need to update with the same version in all files.

== Release process

- [x] update the version in CMakeLists.txt
- [x] update the version in docs/antora.yml
- [x] commit the changes with the message "Release vx.y.z". At this point the CI will generate the docker image and push it to docker hub