site:
  title: Solar Shading
  url: https://feelpp.github.io/solar-shading/
  start_page: solar-shading::index.adoc
content:
  sources:
  - url: .
    start_path: docs
ui:
  supplemental_files: ./antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  attributes:
    dynamic-blocks@: ''
  extensions:
    - '@feelpp/asciidoctor-extensions'

