== Shading masks

Shading masks are synthetic diagrams that represent the incident radiation on a given surface for all possible altitudes and azimuth angles of the incoming rays. They are normally represented using a circular diagram where:

- the azimuth coordinate runs on the circumference;
- the altitude coordinate runs from the circumference to the center of the circle;
- white and light grey regions indicate none to little shading from the surroundings (buildings, trees, etc) for that specific interval of azimuth and altitude angles;
- dark grey and black regions indicate heavy to complete coverage from the surroundings (buildings, trees, etc) for that specific interval of azimuth and altitude angles.

In this implementation, BVH trees are used to check whether a given ray intersects or not the surfaces of the buildings.
The shading masks are stored in CSV files as matrices of size stem:[nAzimuth \times nAltitude], where nAzimuth and nAltitude determine the discretization of the azimuth and altitude intervals.

It is possible to visualize a given shading mask by using the _shadingMask_visualization.py_ Python script.
One can specify a single csv file, a directory containing several csv files, and also the destination folder where the images are saved.



- Marsh, Andrew. "The application of shading masks in building simulation." Proceedings of the Building Simulation 2005 Conference. 2005.

=== Execution of the examples

After building the sources, one can launch the exampleShadingMask case

`./feelpp_ss_example_ShadingMasks --config-file exampleShadingMask/exampleShadingMask.cfg`

It will produce a mask per marked surface (floors are not marked). In order to visualize the results, one can launch the Python script

`python3 visualization/shadingMask_visualization.py --dir_path <PATH_TO_SHADING_MASKS_RESULT_DIRECTORY> --destination <DIRECTORY_STORING_VISUALIZATION_RESULTS>`

One can also launch this example via CTest.

=== Execution of the in-app benchmarks

After building the sources, one can launch the in-app benchmarks when located at the source of the repo:

`./src/run_examples.sh`

This will ask for the executable to use, each one compiled using different compilation flags:
    - 1 : -Ofast -march=native
    - 2 : -O3 -march=native 
    - 3 : -O2 -march=native
    - 4 : -Ofast -march=native -funroll-loops
    - 5 : -O3 -march=native -funroll-loops
    - 6 : -O2 -march=native -funroll-loops
    - 7 : -Ofast -march=native -funroll-loops -funsafe-math-optimizations

All resulting `.png` files are stored at 'results/ShadingMasks/'.

Additionnal quality benchmarks will be added.

The EigenRand_vectorized benchmark is not included in the run_examples.sh script, as it is not executing because of a problematic memory allocation, or deallocation.

One can also launch all test consecutively using the following command when located at the source of the repo:

`./src/run_all.sh`

The prompt will ask you to chose the case you want to launch the tests on. The results are displayed in the terminal, only the fastest execution time is kept for each method, the flags used to get this result are also displayed.

=== Visualization of the differences

In order to visualize the differences between the shading masks, one can launch the bash script when located at the root of the project:

`./src/SM_differences.sh`

The results are stored as .png files in the '/results/Differences' directory.